### ISSUE TITLE
using formtastic form in a cell

### ISSUE THREAD

**Issue by ryan2johnson9** [apotonick/cells#312]
Hi, I am using cells 4.0.2 and I wish to render a formtastic form using semantic_form_for in my cell. I notice that the rails helper form_for works, but the formtastic helper semantic_form_for raises an error
`undefined method 'semantic_form_for' on an instance of LocationVariableCell.`

I get around this by passing the view context into the cell like so:

`cell(:location_variable, @location_variable).(:edit, view_context: self)`

in my cell

    def edit args
      @view_context = args[:view_context]
      render
    end

in my view `@view_context.semantic_form_for(.........`

Is this bad practice? Is it costly to pass the view context into a cell? 
Is there a better way of doing it?

**Comment by apotonick** [comment]
Hi Ryan, this is bad practise, and documented here: https://github.com/apotonick/cells#rails-helper-api

Basically, we automatically include the default Rails helpers in order to fix some bugs in a Rails environment. This is why `form_for` works, but to make formtastic run, you need to include the required helpers manually. Here's an example: https://github.com/apotonick/cells/blob/master/test/rails4.2/app/cells/formtastic_cell.rb

If you want to learn more, read the _Cells_ chapter of the Trailblazer book where I speak about this, too.

BTW: Passing objects around in Ruby is never costly, so what you do is clumsy, but should be equally fast. However, in Cells 4, we want to completely stop using ActionView so please don't do it.

**Comment by ryan2johnson9** [comment]
@apotonick Thank you so much for the quick and clear response.

I almost got there on my own, I tried
`include Formtastic::Helpers::FormHelper`
and got an error
I did not do the
`include ActionView::RecordIdentifier`

That fixed it for me. Cheers

**Comment by apotonick** [comment]
No problem! Sorry for the inconvenience, but this is really a Rails problem and not Cells' fault. I explain it a bit more here: http://nicksda.apotomo.de/2015/06/cells-4-0-goodbye-rails-hello-ruby/ (_Long Live Rails_ section).

**Comment by ryan2johnson9** [comment]
Selects with formtastic don't work unless you also do
`include ActionView::Helpers::FormOptionsHelper`
was a bit tricky to find, error: `private method 'select' called on an instance of LocationVariableCell.`

I guess using cells makes you get to know exactly which helpers you are using.

I'll try editing the link to the formtastic help file you showed me.
