### ISSUE TITLE
Breaking when updated to 4.1.4 and Uber 0.1.0

### ISSUE THREAD

**Issue by mrbongiolo** [apotonick/cells#440]
Just updated both gems and the production env is broken with this message:
```
NoMethodError (undefined method `call' for {}:Uber::Options):
```

**Comment by dreyks** [comment]
yup, had to downgrade `uber` to `0.0.15`

**Comment by dreyks** [comment]
this is still an issue for cells@v4.1.5

**Comment by dreyks** [comment]
the workaround is
```ruby
Uber::Options.class_eval do
  alias_method :call, :evaluate
end
```
